#!/usr/bin/env python3
"""myLPub3D zh_CN translation pipeline.

Master store keeps {id: {c, s, t}} keyed by a stable hash of (context, source),
so work is incremental, resumable, and re-appliable after an lupdate re-run.

Commands
  classify            split the .ts into workable / skipped entries
  next [-n N]         emit the next untranslated batch as JSONL
  merge <file.json>   merge {id: translation} pairs into the master store
  apply               write translations back into the .ts
  status              progress report
  validate            run the guardrails

Entry categories that must never be translated (leaving them untranslated makes
Qt fall back to the source string, which is the correct behaviour) are detected
automatically and excluded from every batch.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
TRANS_DIR = os.path.dirname(HERE)
TS_PATH = os.path.join(TRANS_DIR, "lpub3d_zh_CN.ts")
STORE = os.path.join(HERE, "translations.json")
# source trees scanned by reachable_contexts(); paths are relative to the repo root
SOURCE_TREES = ["mainApp", "lclib", "ldvlib", "qsimpleupdater", "quazip",
                "ldrawini"]

# --------------------------------------------------------------------------
# entry classification
# --------------------------------------------------------------------------

# Rich-text payloads generated by Qt Designer that must stay byte-identical.
RE_HTML_DOC = re.compile(r"DOCTYPE|<style\b|<head\b|<body\b", re.I)

# Qt objectName keys that upstream mistakenly wrapped in tr(). lpub.cpp:4928 and
# :5236 pass these to setObjectName(), and lpub.cpp:7018/7164 later look the
# action up again by the same literal string. Translating them would rename the
# action but not the lookup, so the menu entries would silently disappear.
RE_OBJECT_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9]*%?\d*Act\.\d+$")

# Markers in generated parameter files that the application parses back.
#
# excludedparts.cpp:318 writes this marker into excludedParts.lst, and :65 reads
# it back with
#     ^#[\w\s]+\:[\s](\^.*)$
# which requires an ASCII ':' (and, under Qt's default QRegularExpression
# options, ASCII \w). A translated marker uses the full-width '：'
# ('# 用于加载此文件的正则表达式为：...') and therefore never matches: the user's
# custom regular expression is silently discarded and the hard-coded default is
# used instead, disabling the documented "edit the regular expression in the
# file" feature.
#
# The exclusion is keyed on the SOURCE TEXT, not on (context, source). The same
# phrase is written through QMessageBox::tr() in excludedparts.cpp and through
# ColourPartListWorker::tr() in threadworkers.cpp:1953, so a uid-based exclusion
# silently leaves the other copy translatable - which is exactly how one live
# translation shipped. The marker is also read back by ldrawcolourparts.cpp:41,
# plisubstituteparts.cpp:58, stickerparts.cpp:59 and annotations.cpp:1319+.
RE_PARSER_CONTRACT = re.compile(
    r"^#\s*(?:The Regular Expression used to load this file is:"
    r"|and paste to a new line with starting phrase)"
)

# ---------------------------------------------------------------------------
# Contexts whose strings are IDENTIFIERS, not display text.
#
# Established by tracing each context to its point of use:
#
#   Action (276)  lpub.cpp:5673-5674 shows that display text comes from the
#                 "Menu" and "Status" contexts; the "Action" context holds the
#                 ID field of ActionAttributes, consumed as a lookup key.
#   Mouse (18)    Consumed as lcTool names. lc_shortcuts.cpp:206/243 use the raw
#                 literal (fromLatin1 / operator==) as a shortcut config key, so
#                 the text is load-bearing. lc_qpreferencesdialog.cpp:1597 wraps
#                 it in tr() from inside lcQPreferencesDialog, which resolves
#                 against this class's context, not "Mouse" - and that tab is
#                 removed at runtime (lc_qpreferencesdialog.cpp:138), so those
#                 strings are unreachable in myLPub3D either way.
#   Official Part / Unofficial Part (2)
#                 piece.cpp:1601-1604 returns these via QT_TRANSLATE_NOOP, i.e.
#                 the raw literal. No consumer calls translate() on them, so the
#                 values act as piece-type identifiers.
#
# Translating any of these would not improve the UI and could desynchronise
# stored identifiers.
# ---------------------------------------------------------------------------
EXCLUDE_CONTEXTS = {
    "Action",
    "Mouse",
    "Official Part",
    "Unofficial Part",
}


# Individual uids that must never be translated are covered by
# RE_PARSER_CONTRACT above, which is deliberately context-independent.


def uid(context: str, source: str) -> str:
    return hashlib.sha1((context + "\x00" + source).encode("utf-8")).hexdigest()[:12]


def skip_reason(source: str, context: str = "", entry_id: str = "") -> str | None:
    """Return a reason string when the entry must not be translated."""
    s = source.strip()
    if not s:
        return "empty"
    if RE_HTML_DOC.search(s):
        return "html-document"
    if RE_OBJECT_NAME.match(s):
        return "qt-objectname"
    if RE_PARSER_CONTRACT.match(s):
        return "parser-contract"
    # contains no translatable letters at all -> pure format/punctuation token
    if not re.search(r"[A-Za-z\u00c0-\u024f]", s):
        return "no-letters"
    if context in EXCLUDE_CONTEXTS:
        return "identifier-context"
    return None


# --------------------------------------------------------------------------
# .ts parsing / writing
# --------------------------------------------------------------------------

def load_entries(ts_path: str):
    """Yield dicts describing every message in the .ts file."""
    root = ET.parse(ts_path).getroot()
    out = []
    for ctx in root.findall("context"):
        cname = ctx.findtext("name") or ""
        for msg in ctx.findall("message"):
            src = msg.findtext("source") or ""
            tr = msg.find("translation")
            out.append({
                "c": cname,
                "s": src,
                "id": uid(cname, src),
                "el": msg,
                "tr": tr,
                "existing": (tr.text or "").strip() if tr is not None else "",
            })
    return root, out


def load_store() -> dict:
    if os.path.exists(STORE):
        with open(STORE, encoding="utf-8") as fh:
            return json.load(fh)
    return {}


def save_store(store: dict) -> None:
    tmp = STORE + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(store, fh, ensure_ascii=False, indent=0, sort_keys=True)
    os.replace(tmp, STORE)


def translation_text(entry) -> str:
    """The text currently carried by an entry's <translation>, numerus included."""
    tr = entry["tr"]
    if tr is None:
        return ""
    if (tr.text or "").strip():
        return tr.text.strip()
    for child in tr:
        if child.tag == "numerusform" and (child.text or "").strip():
            return child.text.strip()
    return ""


def clear_translation(entry) -> bool:
    """Blank a translation that an exclusion rule forbids.

    Returns True when something was actually removed, so callers can report how
    many stale entries were cleaned up. Qt treats an entry with no translation
    text as untranslated and falls back to the source string, which is the
    correct behaviour for every excluded category.
    """
    tr = entry["tr"]
    if tr is None:
        return False
    had_text = bool(translation_text(entry))
    for child in list(tr):
        tr.remove(child)
    tr.text = None
    tr.set("type", "unfinished")
    return had_text


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------

def cmd_classify(args):
    root, entries = load_entries(args.ts)
    work, skipped = [], []
    seen = set()
    for e in entries:
        reason = skip_reason(e["s"], e["c"], e["id"])
        if reason:
            skipped.append((reason, e))
            continue
        if e["id"] in seen:
            continue
        seen.add(e["id"])
        work.append(e)

    print(f"total messages   : {len(entries)}")
    print(f"unique workable  : {len(work)}")
    print(f"skipped          : {len(skipped)}")
    from collections import Counter
    for reason, n in Counter(r for r, _ in skipped).most_common():
        print(f"   {reason:16s}: {n}")
    print()
    print("--- skipped samples (must stay untranslated) ---")
    for reason, e in skipped[:12]:
        print(f"  [{reason}] [{e['c']}] {e['s'][:90]!r}")


def cmd_next(args):
    store = load_store()
    root, entries = load_entries(args.ts)

    done = set(store.keys())
    pending = []
    seen = set()
    skip_ctx = {c.strip() for c in (args.exclude_context or "").split(",") if c.strip()}
    for e in entries:
        if skip_reason(e["s"], e["c"], e["id"]):
            continue
        if e["id"] in done or e["id"] in seen:
            continue
        if args.max_src_len and len(e["s"]) > args.max_src_len:
            continue
        if args.exclude_context and e["c"] in skip_ctx:
            continue
        seen.add(e["id"])
        pending.append(e)

    # Pack a batch: fill up to the entry budget, and where possible stop on a
    # context boundary rather than splitting a context, so terminology stays
    # consistent within one batch.
    batch, chars, last_ctx = [], 0, None
    for e in pending:
        if len(batch) >= args.n:
            break
        if len(batch) >= args.min_entries and chars + len(e["s"]) > args.max_chars:
            break
        if batch and e["c"] != last_ctx and len(batch) >= (args.n * 3) // 4:
            break
        batch.append(e)
        chars += len(e["s"])
        last_ctx = e["c"]

    if not batch:
        print("NOTHING PENDING — all workable entries are translated.")
        return

    out_path = args.out
    with open(out_path, "w", encoding="utf-8") as fh:
        for e in batch:
            fh.write(json.dumps({"id": e["id"], "c": e["c"], "s": e["s"]},
                                ensure_ascii=False) + "\n")

    ctxs = sorted({e["c"] for e in batch})
    print(f"batch written : {out_path}")
    print(f"entries       : {len(batch)}")
    print(f"source chars  : {chars}")
    print(f"contexts      : {', '.join(ctxs)}")
    print(f"remaining     : {len(pending) - len(batch)}")


def cmd_merge(args):
    store = load_store()
    added = updated = 0
    with open(args.file, encoding="utf-8") as fh:
        data = json.load(fh)
    if isinstance(data, list):
        data = {d["id"]: d["t"] for d in data}
    for k, v in data.items():
        if not str(v).strip():
            continue
        if k in store:
            if store[k].get("t") != v:
                store[k]["t"] = v
                updated += 1
        else:
            store[k] = {"t": v}
            added += 1
    save_store(store)
    print(f"merged: {added} new, {updated} updated (store size {len(store)})")


def cmd_mergebatch(args):
    """Merge a plain JSON array of translations against a batch file, positionally.

    Far less error-prone than transcribing 500 hash keys by hand: the batch file
    fixes the order, and this command refuses to run when the counts disagree.
    Converted to the id-keyed form and handed to cmd_merge.
    """
    batch = [json.loads(line) for line in open(args.batch, encoding="utf-8") if line.strip()]
    with open(args.file, encoding="utf-8") as fh:
        items = json.load(fh)
    if not isinstance(items, list):
        sys.exit("expected a JSON array of translations, one per batch entry")

    # allow {"t": "..."} objects as well as bare strings
    items = [i.get("t") if isinstance(i, dict) else i for i in items]

    if len(items) != len(batch):
        sys.exit(f"count mismatch: batch has {len(batch)} entries, "
                 f"translations file has {len(items)}")

    merged = {}
    skipped = []
    for entry, tgt in zip(batch, items):
        if tgt is None or not str(tgt).strip():
            skipped.append(entry["id"])
            continue
        merged[entry["id"]] = str(tgt)

    with open(args.file + ".byid.json", "w", encoding="utf-8") as fh:
        json.dump(merged, fh, ensure_ascii=False, indent=0)

    class _A:
        file = args.file + ".byid.json"
    cmd_merge(_A())
    if skipped:
        print(f"skipped {len(skipped)} blank translation(s)")


def cmd_status(args):
    store = load_store()
    root, entries = load_entries(args.ts)
    seen = set()
    workable = 0
    for e in entries:
        if skip_reason(e["s"], e["c"], e["id"]) or e["id"] in seen:
            continue
        seen.add(e["id"])
        workable += 1
    done = len([k for k in store if k in seen])
    print(f"workable unique entries : {workable}")
    print(f"translated              : {done}")
    print(f"remaining               : {workable - done}")
    if workable:
        print(f"progress                : {done / workable * 100:.1f}%")


def cmd_apply(args):
    store = load_store()
    root, entries = load_entries(args.ts)
    applied = cleared = unmatched = 0
    for e in entries:
        if skip_reason(e["s"], e["c"], e["id"]):
            # Enforce the exclusion rather than merely ignoring it. apply() is
            # otherwise additive-only, so a translation written before an
            # exclusion existed (a context added to EXCLUDE_CONTEXTS, or a new
            # contract rule) would stay in the .ts and ship in the .qm, while
            # every guardrail stayed green because excluded entries are skipped.
            if clear_translation(e):
                cleared += 1
            continue

        rec = store.get(e["id"])
        if not rec or not rec.get("t"):
            continue
        tr = e["tr"]
        if tr is None:
            unmatched += 1
            continue

        if e["el"].get("numerus") == "yes":
            # Plural messages carry their text in <numerusform> children, one per
            # plural form of the TARGET language, not as plain <translation>
            # text. Chinese has a single plural form, so exactly one child is
            # correct. Writing plain text here produces an invalid .ts that
            # lrelease rejects with "Unexpected characters".
            for child in list(tr):
                tr.remove(child)
            tr.text = None
            numerus = ET.SubElement(tr, "numerusform")
            numerus.text = rec["t"]
        else:
            tr.text = rec["t"]

        if "type" in tr.attrib:
            del tr.attrib["type"]
        applied += 1

    total = len(entries)
    xml = ET.tostring(root, encoding="unicode")
    header = '<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE TS>\n'
    # ET re-declares xmlns only if namespaces were used; Qt .ts has none.
    with open(args.ts, "w", encoding="utf-8") as fh:
        fh.write(header)
        fh.write(xml)
        fh.write("\n")
    print(f"applied {applied} translations to {args.ts} ({total} messages total, "
          f"{cleared} excluded entries cleared, {unmatched} unmatched)")


# --------------------------------------------------------------------------
# guardrails
# --------------------------------------------------------------------------

RE_PLACEHOLDER = re.compile(r"%[0-9]+|%n|%L\d|%[A-Z]")
# A Qt mnemonic is '&' immediately followed by a letter or digit. '&&' renders a
# literal ampersand, and an ampersand with spaces around it ("Network & Internet")
# is just punctuation - neither is a mnemonic, so neither must be preserved.
RE_AMP = re.compile(r"(?<!&)&(?=[A-Za-z0-9])")
RE_TAG = re.compile(r"</?([a-zA-Z][a-zA-Z0-9]*)[^>]*>")

KEEP_EN = [
    "myLPub3D", "LPub3D", "LPub", "LDraw", "LDView", "LDVQt", "POV-Ray",
    "LSynth", "Blender", "BrickLink", "LEGO", "MPD", "LDR", "DAT",
    "PLI", "CSI", "BOM", "Step", "Sub-model", "Callout",
]


def reachable_contexts(roots):
    """Contexts a runtime lookup can actually produce.

    Qt resolves tr() to the class that DECLARES Q_OBJECT (or Q_DECLARE_TR_FUNCTIONS),
    which is not always the class lupdate names in the .ts. When the two differ the
    entry is written into the .qm under a context nobody ever queries, and the
    translation silently never appears - while every guardrail still passes, because
    the translation itself is perfectly well formed.

    A context is reachable when some call site can produce it:
      * QObject                - a literal QObject::tr(...)
      * translate("X") / QT_TRANSLATE_NOOP("X") / Q_DECLARE_TR_FUNCTIONS(X)
      * <class> in a .ui file  - uic emits translate("<class>", ...) into ui_*.h
      * the name of a class that declares Q_OBJECT
      * the name of a base class in an inheritance chain, which the Q_OBJECT case
        above already covers
    """
    reach = {"QObject"}
    for root in roots:
        for dp, _d, fs in os.walk(root):
            for f in fs:
                if not f.endswith((".cpp", ".h", ".ui")):
                    continue
                p = os.path.join(dp, f)
                try:
                    s = open(p, "rb").read().decode("utf-8", "replace")
                except OSError:
                    continue
                for m in re.finditer(r'(?:translate|QT_TRANSLATE_NOOP|Q_DECLARE_TR_FUNCTIONS)'
                                     r'\s*\(\s*(?:"([^"]+)"|([A-Za-z_]\w*))\s*[,)]', s):
                    reach.add(m.group(1) or m.group(2))
                # explicit qualified calls, e.g. QMessageBox::tr("...") - the runtime
                # context is the qualified class name itself
                for m in re.finditer(r'\b([A-Za-z_]\w*)::tr\s*\(', s):
                    reach.add(m.group(1))
                for m in re.finditer(r'<class>([^<]+)</class>', s):
                    reach.add(m.group(1))
                # match class/struct declarations only at line start, allowing for
                # export macros (QUAZIP_EXPORT, QSU_DECL, ...). The lookahead pins
                # the capture to the name directly preceding ":" or "{" so the macro
                # name is never captured instead of the class name; without the
                # line anchor a comment like "this class is ..." swallows the real
                # declaration that follows.
                for m in re.finditer(r'^[ \t]*(?:class|struct)\s+'
                                     r'(?:[A-Za-z_]\w*[ \t]+)*?([A-Za-z_]\w*)'
                                     r'(?=[ \t]*[{:])', s, re.M):
                    brace = s.find("{", m.end())
                    if brace == -1:
                        continue
                    body = s[brace + 1: brace + 1 + 6000]
                    end = body.find("};")
                    if end != -1:
                        body = body[:end]
                    if re.search(r'\bQ_OBJECT\b', body):
                        reach.add(m.group(1))
    return reach


def cmd_validate(args):
    store = load_store()
    root, entries = load_entries(args.ts)

    problems = {"placeholder": [], "amp": [], "tag": [], "empty": [],
                "html": [], "markup_leak": [], "same": [], "dead_context": [],
                "excluded": []}
    checked = 0
    for e in entries:
        rec = store.get(e["id"])
        if not rec or not rec.get("t"):
            continue
        if skip_reason(e["s"], e["c"], e["id"]):
            continue
        checked += 1
        src, tgt = e["s"], rec["t"]

        if sorted(RE_PLACEHOLDER.findall(src)) != sorted(RE_PLACEHOLDER.findall(tgt)):
            problems["placeholder"].append((e["c"], src[:70], tgt[:70]))

        # compare mnemonic counts, not mere presence: a translation may legitimately
        # add or drop an ampersand that is not a mnemonic
        if sorted(RE_AMP.findall(src)) != sorted(RE_AMP.findall(tgt)):
            problems["amp"].append((e["c"], src[:70], tgt[:70]))

        if sorted(RE_TAG.findall(src)) != sorted(RE_TAG.findall(tgt)):
            problems["tag"].append((e["c"], src[:70], tgt[:70]))

        if RE_HTML_DOC.search(tgt):
            problems["html"].append((e["c"], src[:70], tgt[:70]))

        if not tgt.strip():
            problems["empty"].append((e["c"], src[:70], ""))

        if src.strip() == tgt.strip() and re.search(r"[A-Za-z]{4,}", src):
            problems["same"].append((e["c"], src[:70], tgt[:70]))

    # Unreachable contexts: every translation sitting under a context that no runtime
    # lookup can produce is dead weight, and nothing else in this report would notice.
    # TRANS_DIR is <repo>/mainApp/translations, so the repo root is two levels up
    repo = os.path.dirname(os.path.dirname(TRANS_DIR))
    reach = reachable_contexts([os.path.join(repo, b) for b in SOURCE_TREES])
    dead = {}
    for e in entries:
        if e["c"] in reach:
            continue
        if not (store.get(e["id"]) or {}).get("t"):
            continue
        dead.setdefault(e["c"], []).append(e["s"])
    # Exclusions must be ENFORCED, not merely honoured when picking work. An
    # exclusion can be introduced after the fact (a new contract rule, or a
    # context added to EXCLUDE_CONTEXTS), and the .ts then keeps the translation
    # that was already written - lrelease compiles it and it ships. No check
    # above ever looks at excluded entries, so this class was invisible. Read
    # the .ts, not the store: the stale text lives only in the .ts.
    for e in entries:
        if not translation_text(e):
            continue
        if skip_reason(e["s"], e["c"], e["id"]):
            problems["excluded"].append((e["c"], e["s"][:70], translation_text(e)[:70]))

    for c, srcs in sorted(dead.items()):
        problems["dead_context"].append((c, f"{len(srcs)} entries, e.g. {srcs[0][:44]}", ""))

    print(f"validated {checked} translated entries\n")
    for kind, items in problems.items():
        label = {
            "placeholder": "placeholder mismatch (%1..%n)",
            "amp": "lost & mnemonic",
            "tag": "HTML tag mismatch",
            "empty": "empty translation",
            "html": "translated HTML/CSS document (forbidden)",
            "markup_leak": "markup leak",
            "same": "identical to source (review)",
            "dead_context": "unreachable context (runtime never queries it)",
            "excluded": "excluded entry carrying a translation (must be blank)",
        }[kind]
        print(f"{label:38s}: {len(items)}")
        for c, s, t in items[:6]:
            print(f"    [{c}] SRC={s!r}")
            print(f"    {'':>{len(c)+3}} TGT={t!r}")
    total = sum(len(v) for k, v in problems.items() if k != "same")
    print(f"\nblocking problems: {total}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ts", default=TS_PATH)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("classify")

    p_next = sub.add_parser("next")
    p_next.add_argument("-n", type=int, default=200)
    p_next.add_argument("--min-entries", type=int, default=40)
    p_next.add_argument("--max-chars", type=int, default=16000)
    p_next.add_argument("--max-src-len", type=int, default=0,
                        help="only take entries whose source is at most this many "
                             "characters (0 = no limit). Used to clear the short, "
                             "high-frequency UI text before the long help blocks.")
    p_next.add_argument("--exclude-context", default="",
                        help="comma-separated context names to skip entirely, "
                             "e.g. --exclude-context QObject")
    p_next.add_argument("--out", default=os.path.join(HERE, "batch.jsonl"))

    p_merge = sub.add_parser("merge")
    p_merge.add_argument("file")

    p_mb = sub.add_parser("mergebatch")
    p_mb.add_argument("batch")
    p_mb.add_argument("file")

    sub.add_parser("status")
    sub.add_parser("apply")
    sub.add_parser("validate")

    args = ap.parse_args()
    {"classify": cmd_classify, "next": cmd_next, "merge": cmd_merge,
     "mergebatch": cmd_mergebatch, "status": cmd_status, "apply": cmd_apply,
     "validate": cmd_validate}[args.cmd](args)


if __name__ == "__main__":
    main()
